project: 'TestProject'
name: 'FirstExperiment'

joints: ['FOOT_LEFT', 'FOOT_RIGHT']
sampling_points: 2048 
train_size: 0.9
val_size: 0.1
test_size: 0

# Training parameters
epochs: 30
batch_size: 16
learning_rate: 0.0005
loss: 'mean_squared_error'

# Evaluation
metrics: 'percentual_correct_keypoints'
threshold: 100

# Checkpoint parameters
checkpoint_dir: './checkpoints'

# Logging root
logs_dir: './logs'