PROJECT:
  NAME: 'test' 
  EXPERIMENT: 'first_yacs'

DATA:
  JOINTS: ['PELVIS', 'HIP_LEFT', 'HIP_RIGHT', 'KNEE_LEFT', 'KNEE_RIGHT', 'ANKLE_LEFT', 'ANKLE_RIGHT']
  SAMPLING_POINTS: 128
  NORMALIZATION: ''

TRAIN:
  EPOCHS: 30
  BATCH_SIZE: 16
  LEARNING_RATE: 0.005
