# Experiment nomenclatures
project: 'TestProject'
name: 'FirstExperiment'

# Training parameters
joints: ['PELVIS', 'HIP_LEFT', 'HIP_RIGHT']
sampling_points: 1024
train_size: 0.9
val_size: 0.1
epochs: 30
batch_size: 16
learning_rate: 0.0005
loss: 'mean_squared_error'

# Evaluation
metrics: 'percentual_correct_keypoints'
threshold: 50

# Checkpoint parameters
checkpoint_dir: './checkpoints'

# Logging root
logs_dir: './logs'

# Dataset
datasets: ['D:/azure_kinect/AEBA3A/02', 'D:/azure_kinect/AEBA3A/03']